spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  #type-aliases-package: com.example.shopping.entity
  #mapper-locations: classpath*:com/example/shopping/mapper/xml/*.xml
  #type-enums-package: com.base.enmu #实体类枚举包

  configuration:
    map-underscore-to-camel-case: true #下划线转驼峰